# Debian package
set(CPACK_GENERATOR "DEB")
set(CPACK_DEBIAN_PACKAGE_SECTION "misc")

if("${ARCH}" STREQUAL "arm")
	set(ARCH "armhf")
endif()
set(CPACK_DEBIAN_PACKAGE_ARCHITECTURE "${ARCH}")

message("Target arch: ${ARCH} ${CPACK_DEBIAN_PACKAGE_ARCHITECTURE}")

set(CPACK_DEBIAN_PACKAGE_DEPENDS
	"libevdev2 (>= 1.3)"
)

set(CPACK_PACKAGE_FILE_NAME "${CMAKE_PROJECT_NAME}-${CPACK_PACKAGE_VERSION}_${CPACK_DEBIAN_PACKAGE_ARCHITECTURE}")
